### ISSUE TITLE
getAccessToken 에러

### ISSUE THREAD

**Issue by akyeongah** [actbase/react-kakaosdk#8]
리액트 네이티브 환경에서 getAccessToken를 사용한 경우 에러가 발생합니다.

에러 메시지입니다.
[TypeError: str.replace is not a function. (In 'str.replace(' ', 'T')', 'str.replace' is undefined)]

구현 코드입니다.
`export async function getAccessToken () {

    KakaoSDK.getAccessToken()

        .then((res) => {
            console.log('getAccessToken res: ', res)
        })

        .catch((err) => {
            console.log('getAccessToken err: ', err)
        })

}`

getAccessToken가 아닌 login, getProfile은 정상작동하는 상황입니다.

**Comment by ChanghyeonYoon** [comment]
KakaoSDK v2부터는 getAccessToken을 지원하지 않습니다.
login에서 리턴되는 토큰으로 사용 부탁드립니다.

해당 내용 리드미 수정하겠습니다.

**Comment by ChanghyeonYoon** [comment]
Duplicate of #5

**Comment by akyeongah** [comment]
그럼 로그인 없이 Access토큰을 재발급할 수 있는 방법은 없는 것인가요?

**Comment by ChanghyeonYoon** [comment]
@akyeongah 네. 로그인 성공 시 필요한 정보들을 디바이스에 저장해서 사용 부탁드립니다.
